NumPy - 대규모의 다차원 배열을 쉽게 처리할 때 사용하는 파이썬 라이브러리<br>
*** 한 문제씩 실행되도록 """를 이용한 주석을 사용했으니 """를 뒤로 이동해가며 모든 문제를 해결하세요. ***

## 내용
1. 배열 초기화
2. 데이터 읽기 및 수정
3. 데이터 주무르기 
4. Combining data
5. Math operations

출처: Introduction to Deep Learning at Carnegie Mellon University (https://deeplearning.cs.cmu.edu/S22/index.html)

In [1]:
# Import the NumPy 
import numpy as np

# 랜덤 시드 설정: 난수를 사용해도 실행할 때마다 동일한 결과를 얻기 위함
np.random.seed(0)

# 1. 배열 초기화


새로운 넘파이 배열 만들기

## a. 비어 있는 (초기화 안된) / 0으로 채워진 / 1로 채워진 배열 만들기


1. numpy.empty (https://numpy.org/doc/stable/reference/generated/numpy.empty.html)
2. numpy.zeros (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros)
3. numpy.ones (https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones)
4. numpy.full (https://numpy.org/doc/stable/reference/generated/numpy.full.html#numpy.full)
5. numpy.zeros_like (https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html#numpy.zeros_like)
6. numpy.ones_like (https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html#numpy.ones_like)
7. numpy.full_like (https://numpy.org/doc/stable/reference/generated/numpy.full_like.html#numpy.full_like)


In [5]:
# 2 x 2 크기로 초기화 안된 빈 배열 만들기
# 장점? A: 배열 값을 0으로 설정하지 않으므로 약간 더 빠를 수 있습니다.
# 단점? A:사용자가 배열의 모든 값을 수동으로 설정해야 하므로 주의해서 사용해야 합니다
# 힌트: API 문서의 Notes
empty_arr = np.empty((2,2))
print("An empty array is \n", empty_arr, " with dimensions ", empty_arr.shape, "\n")

# 모두 0으로 채워진 2 x 3 배열 만들기
zeros_arr =  np.zeros((2, 3))
print("A zeros array is \n", zeros_arr, " with dimensions ", zeros_arr.shape, "\n")

# 모두 1로 채워진 4 x 2 배열 만들기
ones_arr = np.ones((4, 2))
print("A ones array is \n", ones_arr, " with dimensions ", ones_arr.shape, "\n")

# 모두 10으로 채워진 2 x 2 배열 만들기
tens_arr = np.full((2, 2), 10)
print("A filled array is \n", tens_arr, " with dimensions ", tens_arr.shape, "\n")

# 주어진 배열과 동일한 모양에 0으로 채워진 배열 만들기
zeros_like_arr = np.zeros_like(ones_arr)
print("A zero like array is \n", zeros_like_arr, " with dimensions ", zeros_like_arr.shape, "\n")

# 주어진 배열과 동일한 모양에 1로 채워진 배열 만들기
ones_like_arr = np.ones_like(zeros_arr)
print("A ones like array is \n", ones_like_arr, " with dimensions ", ones_like_arr.shape, "\n")

# 주어진 배열과 동일한 모양에 0.1로 채워진 배열 만들기
full_like_arr = np.full_like(zeros_arr, 0.1)
print("A full like array is \n", full_like_arr, " with dimensions ", full_like_arr.shape, "\n")


An empty array is 
 [[5.e-324 5.e-324]
 [5.e-324 0.e+000]]  with dimensions  (2, 2) 

A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]]  with dimensions  (2, 3) 

A ones array is 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]  with dimensions  (4, 2) 

A filled array is 
 [[10 10]
 [10 10]]  with dimensions  (2, 2) 

A zero like array is 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]  with dimensions  (4, 2) 

A ones like array is 
 [[1. 1. 1.]
 [1. 1. 1.]]  with dimensions  (2, 3) 

A full like array is 
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]  with dimensions  (2, 3) 



## b. 기존의 데이터로 배열 만들기
1. numpy.array (https://numpy.org/doc/stable/reference/generated/numpy.array.html)
2. numpy.loadtxt (https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html)
3. numpy.load (https://numpy.org/doc/stable/reference/generated/numpy.load.html)

In [7]:
# 리스트로 배열 만들기
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("An array from given list is \n", arr_from_list, " with dimensions ", arr_from_list.shape, "\n")

An array from given list is 
 [1 2 3 4]  with dimensions  (4,) 



In [11]:
from io import StringIO

# c는 "0 1\n2 3"이 쓰여진 텍스트파일로 취급됨
c = StringIO("0 1\n2 3")  

# txt 파일에서 읽어오기
txt_arr = np.loadtxt(c)
print("txt 파일에서 읽어온 배열\n", txt_arr)


# txt_arr을 a.npy 파일로 저장
np.save('a.npy', txt_arr)

# a.npy에서 'a.npy' 읽어오기
loaded_arr = np.load('./a.npy')
print("\na.npy 파일에서 읽어온 배열\n", loaded_arr)


txt 파일에서 읽어온 배열
 [[0. 1.]
 [2. 3.]]

a.npy 파일에서 읽어온 배열
 [[0. 1.]
 [2. 3.]]


## c. 주어진 숫자 범위에서 만들기
1. numpy.arange (https://numpy.org/doc/stable/reference/generated/numpy.arange.html)
2. numpy.linspace (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [13]:
# 0부터 9까지
range_arr = np.arange(9)
print("An array given range is \n", range_arr, " with dimensions ", range_arr.shape, "\n")


# 2부터 3까지 [2, 3) 다섯 개 동일 간격 숫자로 (2는 포함, 3은 미포함)
linspace_arr = np.linspace(2.0, 3.0, num=5, endpoint=False)
print("An evenly spaced array given range is \n", linspace_arr, " with dimensions ", linspace_arr.shape, "\n")


An array given range is 
 [0 1 2 3 4 5 6 7 8]  with dimensions  (9,) 

An evenly spaced array given range is 
 [2.  2.2 2.4 2.6 2.8]  with dimensions  (5,) 



## d. 무작위 값으로 채운 배열 만들기

1. numpy.random.rand (https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)
2. numpy.random.randint (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)
3. numpy.random.randn (https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html)

In [16]:
# [0, 1)에서 추출한 무작위 실수로 3 x 2 배열 만들기
uniform_rand_arr = np.random.rand(3,2)
print("A random array from a uniform distribution is \n", uniform_rand_arr, " with dimensions ", uniform_rand_arr.shape, "\n")


# [0, 5)에서 추출한 무작위 정수로 2 x 4 배열 만들기
range_rand_int_arr =  np.random.randint(5, size=(2, 4))
print("A random integer array from a range is \n", range_rand_int_arr, " with dimensions ", range_rand_int_arr.shape, "\n")

# 정규분포 N(mu, sigma^2)에서 추출한 무작위 실수로 배열 만들 때:
# mu + sigma * np.random.randn(...) 

# 평균: 3, 표준편차: 2.5인 정규분포에서 추출한 무작위 실수로 2 x 4 배열 만들기 
mu = 3
sigma =2.5
sample_normal_arr = mu + sigma * np.random.randn(2, 4)
print("A random array from a gaussian distribution is \n", sample_normal_arr)
print("with mu: ", mu)
print("with sigma: ", sigma)
print("with dimensions ", sample_normal_arr.shape)


A random array from a uniform distribution is 
 [[0.43758721 0.891773  ]
 [0.96366276 0.38344152]
 [0.79172504 0.52889492]]  with dimensions  (3, 2) 

A random integer array from a range is 
 [[0 1 1 0]
 [1 4 3 0]]  with dimensions  (2, 4) 

A random array from a gaussian distribution is 
 [[4.21078039 4.4478512  2.54604357 6.52551158]
 [2.06382077 3.68799579 0.59811347 3.94231744]]
with mu:  3
with sigma:  2.5
with dimensions  (2, 4)


# 2. 데이터 읽기 및 수정

## a. 인덱싱: NumPy 배열에서 값 읽어오기

In [17]:
# 무작위 값으로 채워진 4 x 5 x 6 배열을 만들어보세요. (5 x 6 행렬이 4개 있는 것으로 해석할 수 있음)
# MNIST에서 train_images.shape의 결과 (60000, 28, 28)는 28 x 28 그림이 60,000장 있다는 것을 의미했음
# (묶음, 행, 열)로 해석할 수 있음
n = np.random.rand(4, 5, 6)
n

array([[[0.94466892, 0.52184832, 0.41466194, 0.26455561, 0.77423369,
         0.45615033],
        [0.56843395, 0.0187898 , 0.6176355 , 0.61209572, 0.616934  ,
         0.94374808],
        [0.6818203 , 0.3595079 , 0.43703195, 0.6976312 , 0.06022547,
         0.66676672],
        [0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077,
         0.57019677],
        [0.43860151, 0.98837384, 0.10204481, 0.20887676, 0.16130952,
         0.65310833]],

       [[0.2532916 , 0.46631077, 0.24442559, 0.15896958, 0.11037514,
         0.65632959],
        [0.13818295, 0.19658236, 0.36872517, 0.82099323, 0.09710128,
         0.83794491],
        [0.09609841, 0.97645947, 0.4686512 , 0.97676109, 0.60484552,
         0.73926358],
        [0.03918779, 0.28280696, 0.12019656, 0.2961402 , 0.11872772,
         0.31798318],
        [0.41426299, 0.0641475 , 0.69247212, 0.56660145, 0.26538949,
         0.52324805]],

       [[0.09394051, 0.5759465 , 0.9292962 , 0.31856895, 0.66741038,
         0.131797

In [23]:
# n에서 두 번째 묶음의 세 번째 행, 네 번째 열의 값은? 인덱스는 0에서 시작
n[1][2][3]

0.9767610881903371

## b. 슬라이싱: NumPy 배열의 일부를 가져오기

시작(포함):끝(미포함)으로 연속된 항목을 슬라이싱 <br>
:만 쓰면 전체

In [21]:
# 첫 번째 묶음의 모든 행렬 가져오기
print(n[0, :, :]) # same as: n[0], 정답이므로 수정할 필요 없음

[[0.94466892 0.52184832 0.41466194 0.26455561 0.77423369 0.45615033]
 [0.56843395 0.0187898  0.6176355  0.61209572 0.616934   0.94374808]
 [0.6818203  0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
 [0.67063787 0.21038256 0.1289263  0.31542835 0.36371077 0.57019677]
 [0.43860151 0.98837384 0.10204481 0.20887676 0.16130952 0.65310833]]


In [24]:
# 첫 번째 묶음에서 [0, 3) 행, [0, 4) 열 가져오기, 즉 3 x 4 배열이 나와야 함
print(n[0,:3 ,:4 ])

[[0.94466892 0.52184832 0.41466194 0.26455561]
 [0.56843395 0.0187898  0.6176355  0.61209572]
 [0.6818203  0.3595079  0.43703195 0.6976312 ]]


In [25]:
# 전체 묶음에서 4번 째 행, 5번째 열 값들 가져오기
print(n[:, 3:4, 4:5]) 

[[[0.36371077]]

 [[0.11872772]]

 [[0.95274901]]

 [[0.43141844]]]


### Slicing at Interval
시작::증가폭으로 띄엄띄엄 슬라이싱<br>
예) a[7::2]인 경우 a[7], a[9], a[11], ... 을 가져와서 배열로 만듦

In [26]:
print(n[0::2]) # 0번 묶음, 2번 묶음, 4번 묶음, ... 슬라이싱 (n은 3번 묶음까지만 있어서 두 개의 묶음만 출력됨)

[[[0.94466892 0.52184832 0.41466194 0.26455561 0.77423369 0.45615033]
  [0.56843395 0.0187898  0.6176355  0.61209572 0.616934   0.94374808]
  [0.6818203  0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
  [0.67063787 0.21038256 0.1289263  0.31542835 0.36371077 0.57019677]
  [0.43860151 0.98837384 0.10204481 0.20887676 0.16130952 0.65310833]]

 [[0.09394051 0.5759465  0.9292962  0.31856895 0.66741038 0.13179786]
  [0.7163272  0.28940609 0.18319136 0.58651293 0.02010755 0.82894003]
  [0.00469548 0.67781654 0.27000797 0.73519402 0.96218855 0.24875314]
  [0.57615733 0.59204193 0.57225191 0.22308163 0.95274901 0.44712538]
  [0.84640867 0.69947928 0.29743695 0.81379782 0.39650574 0.8811032 ]]]


In [27]:
print(n[0::2, 1:4, 1::2]) # 원래 n의 모습과 비교해가며 어떻게 만들어진 것인지 이해하고 넘어가세요.

[[[0.0187898  0.61209572 0.94374808]
  [0.3595079  0.6976312  0.66676672]
  [0.21038256 0.31542835 0.57019677]]

 [[0.28940609 0.58651293 0.82894003]
  [0.67781654 0.73519402 0.24875314]
  [0.59204193 0.22308163 0.44712538]]]


## c. NumPy 배열 수정하기

In [28]:
# 배열 복사하기
n_copy = np.copy(n)

### 하나의 값 수정하기

In [37]:
# 복사한 배열과 n이 같은지 항목 하나로 확인
print(n_copy[2, 4, 1] == n[2, 4, 1])

# 복사한 배열 n_copy[2, 4, 1]의 값을 0.005로 변경
n_copy[2, 4, 1] = 0.005

# 여전히 내용이 같은지 확인
print(n_copy[2, 4, 1] == n[2, 4, 1])

# n_copy는 n을 복사한 것이지만 n과 다른 위치에 독립적으로 존재한다.
# 만약 copy 함수로 복사하지 않고 m = n으로 m을 만든다음
# m[2, 4, 1] 값을 수정하면 어떻게 될까? 
# A: n의 인덱스 값도 바뀐다.
m = n
m[2, 4, 1] = 0.001
print(m[2,4,1])
print(n[2,4,1])
print(n_copy[2,4,1])


True
True
0.001
0.001
0.005


In [38]:
print(n[2,4,1])
print(n_copy[2, 4, 1])

0.001
0.005


### 여러 항목의 값을 같은 값으로 수정하기

In [39]:
n_copy = np.copy(n)

# n_copy 3번째 묶음의 4번째 열의 값 확인
print(n_copy[2, 3])

# n_copy 3번째 묶음, 4번째 열의 값을 모두 0.5로 바꾸기
n_copy[2, 3] = 0.5

# n_copy 3번째 묶음의 4번째 열의 값 확인
print(n_copy[2, 3])

[0.57615733 0.59204193 0.57225191 0.22308163 0.95274901 0.44712538]
[0.5 0.5 0.5 0.5 0.5 0.5]


# 3.데이터 주무르기

## a. Reshaping Arrays (배열 모양 다르게 해석하기)
Array reshaping은 배열안의 데이터는 그대로 두고 모양을 바꿔 해석을 다르게 하는 것입니다.

예를 들어 (4,) 모양의 배열 [1, 2, 3, 4]는 (2, 2) 모양의 배열 [[1, 2], [3, 4]] 및 <br> (1, 4) 모양의 배열 [[1, 2, 3, 4]]로 모양을 바꿔 해석할 수도 있습니다.

#### 동일 차원으로 reshaping

In [40]:
s = np.random.rand(3, 4, 5)
print(f"원래 모양: {s.shape}")

원래 모양: (3, 4, 5)


In [41]:
# 전체 원소 개수
# Q: 어떻게 계산가능할까요?
# A: size 함수를 통해 계산가능하다.
s.size

60

In [42]:
# s 내용 확인하기
print(s)

[[[0.91948261 0.7142413  0.99884701 0.1494483  0.86812606]
  [0.16249293 0.61555956 0.12381998 0.84800823 0.80731896]
  [0.56910074 0.4071833  0.069167   0.69742877 0.45354268]
  [0.7220556  0.86638233 0.97552151 0.85580334 0.01171408]]

 [[0.35997806 0.72999056 0.17162968 0.52103661 0.05433799]
  [0.19999652 0.01852179 0.7936977  0.22392469 0.34535168]
  [0.92808129 0.7044144  0.03183893 0.16469416 0.6214784 ]
  [0.57722859 0.23789282 0.934214   0.61396596 0.5356328 ]]

 [[0.58990998 0.73012203 0.311945   0.39822106 0.20984375]
  [0.18619301 0.94437239 0.7395508  0.49045881 0.22741463]
  [0.25435648 0.05802916 0.43441663 0.31179588 0.69634349]
  [0.37775184 0.17960368 0.02467873 0.06724963 0.67939277]]]


In [44]:
# s를 (2, 6, 5)로 reshape하여 s1에 저장하기
s1 = s.reshape(2, 6,5)
print(f"s1의 모양: {s1.shape}")

s1의 모양: (2, 6, 5)


In [45]:
# s와 s1의 각 원소값과 위치는 동일한 것을 확인해보세요.
print(s1)

[[[0.91948261 0.7142413  0.99884701 0.1494483  0.86812606]
  [0.16249293 0.61555956 0.12381998 0.84800823 0.80731896]
  [0.56910074 0.4071833  0.069167   0.69742877 0.45354268]
  [0.7220556  0.86638233 0.97552151 0.85580334 0.01171408]
  [0.35997806 0.72999056 0.17162968 0.52103661 0.05433799]
  [0.19999652 0.01852179 0.7936977  0.22392469 0.34535168]]

 [[0.92808129 0.7044144  0.03183893 0.16469416 0.6214784 ]
  [0.57722859 0.23789282 0.934214   0.61396596 0.5356328 ]
  [0.58990998 0.73012203 0.311945   0.39822106 0.20984375]
  [0.18619301 0.94437239 0.7395508  0.49045881 0.22741463]
  [0.25435648 0.05802916 0.43441663 0.31179588 0.69634349]
  [0.37775184 0.17960368 0.02467873 0.06724963 0.67939277]]]


### 다른 차원으로 reshaping

In [50]:
# 0부터 119까지 120개의 정수로 이루어진 배열을 간단하게 만들어보세요.
r = np.arange(120)

In [47]:
print(f"원래 모양: {r.shape}")

원래 모양: (119,)


In [48]:
print(r)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118]


In [51]:
# (120,) -> (3, 4, 10)
# 원소개수는 120개로 동일합니다.
r1 = r.reshape(3,4,10)
print(f"r1의 모양: {r1.shape}")

r1의 모양: (3, 4, 10)


In [52]:
# r과 r1을 비교해보세요.
print(r1)

[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]
  [100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]]]


In [53]:
# r1을 reshape하여 r2에 저장하세요.
# (3, 4, 10) -> (6, 20)
r2 = r1.reshape(6,20)
print(f"r2의 모양: {r2.shape}")

r2의 모양: (6, 20)


In [54]:
# r2와 r1, r을 비교해보세요.
print(r2)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]]


수고하셨습니다. 

아래의 셀부터는 수업 시간에 실습하지 않으셔도 됩니다.

바닥부터 딥 러닝 모델을 직접 만들거나 PyTorch를 사용할 예정이면 공부하시는 것이 좋습니다.

## b. 행과 열 바꾸기 (전치)
The transpose operation reverses the order of an array. It switches the rows to columns and vice versa. In a multi-dimensional array, the transpose operation moves the data from one axis to another in the order specified in the transpose method.

In [ ]:
# 아래 주석과 같은 결과가 나오도록 만들어보세요.
w = np.arange().reshape((, ,))
w

# 아래 주석은 실습용 코드가 아닙니다.
"""
array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89]]])
"""

#### 그냥 전치하기

In [ ]:
# w와 비교해보세요.
# (3, 5, 6) -> (6, 5, 3)

# w[1][2][3]은 w1의 무엇과 동일할까요?
# A: w1[][][]

w1 = np.transpose(w)
w1

#### 전치할 때 축 지정하기

In [ ]:
# 원래 0, 1, 2인데 각 묶음은 그대로 두고 묶음 내에서 행과 열을 전치
# (3, 5, 6) -> (3, 6, 5)
# w와 w2를 비교해보세요.
w2 = np.transpose(w, axes=(0, 2, 1)) 
w2

In [ ]:
# (3, 5, 6) -> (5, 6, 3)
# 아래 주석과 같은 결과가 나오도록 만들어보세요.
w3 = np.transpose(w, axes=(, ,))
w3

# 아래 주석은 실습용 코드가 아닙니다.
"""
array([[[ 0, 30, 60],
        [ 1, 31, 61],
        [ 2, 32, 62],
        [ 3, 33, 63],
        [ 4, 34, 64],
        [ 5, 35, 65]],

       [[ 6, 36, 66],
        [ 7, 37, 67],
        [ 8, 38, 68],
        [ 9, 39, 69],
        [10, 40, 70],
        [11, 41, 71]],

       [[12, 42, 72],
        [13, 43, 73],
        [14, 44, 74],
        [15, 45, 75],
        [16, 46, 76],
        [17, 47, 77]],

       [[18, 48, 78],
        [19, 49, 79],
        [20, 50, 80],
        [21, 51, 81],
        [22, 52, 82],
        [23, 53, 83]],

       [[24, 54, 84],
        [25, 55, 85],
        [26, 56, 86],
        [27, 57, 87],
        [28, 58, 88],
        [29, 59, 89]]])
"""

## c. 배열 펼치기 (flattening)
배열 펼치기는 다차원 배열을 일차원으로 만들어줍니다.<br>
(MNIST에서도 28 x 28 2차원 배열을 reshape를 통해 길이 784의 일차원 배열로 만들었습니다.




In [ ]:
k = np.random.rand(5, 6)

In [ ]:
k

### 기본 순서대로 펼치기

In [ ]:
# k와 k1을 비교해보세요.
k1 = k.flatten() 
k1

In [ ]:
k1.shape

### Flattening Arrays along the column

In [ ]:
k2= k.flatten('F') # forms a 1D array where elements in a column are listed before moving to the next column.
k2

### Flattening Arrays using Ravel

In [ ]:
k3 = k.ravel()
k3

### Flattening Arrays using Numpy Reshape


In [ ]:
k4= k.reshape(-1)
k4

### Flatten vs Ravel
Bothe functions take in the same kind of arguments and order to flatten can be specified in both arrays. The difference lies in how the result 1D arrays are are created in both cases.

In [ ]:
test = np.random.rand(4, 5)

In [ ]:
test_flatten = test.flatten()
test_ravel = test.ravel()

print(f"test_flatten: {test_flatten}")
print(f"test_ravel: {test_ravel}")

In [ ]:
test_flatten[0] = 5
print(f"Modified test_flatten: {test_flatten}")
print(f"Original Array: {test}")

In [ ]:
test_ravel[0] = 5
print(f"Modified test_ravel: {test_ravel}")
print(f"Original Array: {test}")

## d. Squeezing & Expanding Arrays

### Squeezing Numpy Arrays

The squeeze operation allows reduction of numpy arrays axes by dropping an specified axis, so long as it is of **unit length**. The product of the shape (overall size of the array) remains the same.

In [ ]:
sq = np.random.rand(4, 1, 5)
print(f"Original Array: \n{sq}\n")
print(f"Shape of Original Array: {sq.shape}")

In [ ]:
# transforms from (4, 1, 5) -> (4, 5)
sq1 = np.squeeze(sq)
print(f"Squeezed Array: \n {sq1}\n")
print(f"Shape of Squeezed Array: {sq1.shape}")

#### Squeezing Multiple Axes
Multiple unit length axes can be squeezed as shown below

In [ ]:
q = np.random.rand(1, 4, 1, 5)
print(f"Original Array: \n {q}\n")
print(f"Shape of Original Array: {q.shape}")


In [ ]:
q1 = np.squeeze(q)
print(f"Multiple Squeezed Array: \n {q1}\n")
print(f"Shape of Multiple Squeezed Array: {q1.shape}")

#### Squeezing specified axes

In [ ]:
q2 = np.squeeze(q, axis=2)
print(f"Specified axis Squeezed Array: {q2}\n")
print(f"Shape of Specified axis Squeezed Array: {q2.shape}")

### Unsqueezing (Expanding) Numpy Arrays
This is the direct opposite of squeezing. A new unit axis is inserted in specified position. Multiple unit axes can be inserted by using a tuple on the axis attribute of the `expand_dims` method.

In [ ]:
y = np.random.rand(4, 5)
print(f"Original Array: \n {y}\n")
print(f"Shape of Original Array: {y.shape}")

In [ ]:
# transforms from (4, 5) -> (4, 1, 5)
y1 = np.expand_dims(y, axis=1)
print(f"Expanded Array: \n {y1}\n")
print(f"Shape of Expanded Array: {y1.shape}")

In [ ]:
# transforms from (4, 5) -> (1, 4, 1, 5)
y2 = np.expand_dims(y, axis=(0, 2))
print(f"Multi-axes Expanded Array: \n {y2}\n")
print(f"Shape of Multi-axes Expanded Array: {y2.shape}")

# 5.Combining data

### 5a. Concatenation

A concatenation operation joins a sequence of arrays along an *existing* axis. All arrays must either have the same shape (except in the concatenating dimension) or be empty.

---



In [ ]:
# Concatenating 2-d Arrays

array1 = np.array([[1, 2], [3, 4]])
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.array([[5, 6]])
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")


concatenated_array1 = np.concatenate((array1, array2), axis = 0) 
print("Concatenated array 1 along axis 0 (row-wise for 2-d arrays) is \n", concatenated_array1, "with dimensions ", concatenated_array1.shape, '\n')

concatenated_array2 = np.concatenate((array1, array2), axis = 1) 
print("Concatenated array 2 along axis 0 (column-wise for 2-d arrays) is \n", concatenated_array1, "with dimensions ", concatenated_array1.shape)


Array 1 is 
 [[1 2]
 [3 4]]  with dimensions  (2, 2) 

Array 2 is 
 [[5 6]]  with dimensions  (1, 2) 

Concatenated array 1 along axis 0 (row-wise for 2-d arrays) is 
 [[1 2]
 [3 4]
 [5 6]] with dimensions  (3, 2) 



ValueError: ignored

In [ ]:
# Concatenating Numpy Arrays

array1 = np.random.randint(3, size = (3, 4, 5))
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.random.randint(4, size = (3, 4, 5))
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

concatenated_array1 = np.concatenate((array1, array2), axis = 0) 
print("Concatenated array 1 is \n", concatenated_array1, "\n\n", "and the dimensions of the concatenated array 1 are: \n", concatenated_array1.shape)

concatenated_array2 = np.concatenate((array1, array2), axis = 1) 
print("Concatenated array 2 is \n", concatenated_array2, "\n\n", "and the dimensions of the concatenated array 2 are: \n", concatenated_array2.shape)

concatenated_array3 = np.concatenate((array1, array2), axis = 2) 
print("Concatenated array 3 is \n", concatenated_array3, "\n\n", "and the dimensions of the concatenated array 3 are: \n", concatenated_array3.shape)


Array 1 is 
 [[[0 1 0 1 1]
  [2 0 2 0 0]
  [0 2 1 2 2]
  [0 1 1 1 1]]

 [[0 1 0 0 1]
  [2 0 2 0 1]
  [1 2 0 1 1]
  [1 0 2 0 2]]

 [[2 0 2 0 0]
  [0 1 1 2 0]
  [0 1 0 1 2]
  [2 0 1 1 1]]]  with dimensions  (3, 4, 5) 

Array 2 is 
 [[[1 3 2 3 3]
  [2 2 3 0 2]
  [3 1 0 1 2]
  [0 3 0 2 0]]

 [[3 3 0 3 0]
  [0 0 0 2 3]
  [0 3 2 3 3]
  [1 1 1 0 1]]

 [[1 1 3 0 3]
  [1 2 0 1 2]
  [0 2 0 1 3]
  [2 2 1 0 3]]]  with dimensions  (3, 4, 5) 

Concatenated array 1 is 
 [[[0 1 0 1 1]
  [2 0 2 0 0]
  [0 2 1 2 2]
  [0 1 1 1 1]]

 [[0 1 0 0 1]
  [2 0 2 0 1]
  [1 2 0 1 1]
  [1 0 2 0 2]]

 [[2 0 2 0 0]
  [0 1 1 2 0]
  [0 1 0 1 2]
  [2 0 1 1 1]]

 [[1 3 2 3 3]
  [2 2 3 0 2]
  [3 1 0 1 2]
  [0 3 0 2 0]]

 [[3 3 0 3 0]
  [0 0 0 2 3]
  [0 3 2 3 3]
  [1 1 1 0 1]]

 [[1 1 3 0 3]
  [1 2 0 1 2]
  [0 2 0 1 3]
  [2 2 1 0 3]]] 

 and the dimensions of the concatenated array 1 are: 
 (6, 4, 5)
Concatenated array 2 is 
 [[[0 1 0 1 1]
  [2 0 2 0 0]
  [0 2 1 2 2]
  [0 1 1 1 1]
  [1 3 2 3 3]
  [2 2 3 0 2]
  [3 1 0 1 2]
 

### 5b. Stacking

The stack operation joins a sequence of arrays along a *new* axis. The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension. All arrays need to be of the same size.  The stacked array has one more dimension than the input arrays.

In [ ]:
# Stacking 1-d Arrays

array1 = np.array([1, 2, 3])
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.array([4, 5, 6])
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")


stacked_array1 = np.stack((array1, array2), axis = 0)
print("Stacked array 1 is \n", stacked_array1, " with dimensions ", stacked_array1.shape)

stacked_array2 = np.stack((array1, array2), axis = 1) 
print("Stacked array 2 is \n", stacked_array2, " with dimensions ", stacked_array2.shape)

stacked_array3 = np.stack((array1, array2), axis = -1) 
print("Stacked array 3 is \n", stacked_array3, " with dimensions ", stacked_array3.shape)


Array 1 is 
 [1 2 3]  with dimensions  (3,) 

Array 2 is 
 [4 5 6]  with dimensions  (3,) 

Stacked array 1 is 
 [[1 2 3]
 [4 5 6]]  with dimensions  (2, 3)
Stacked array 2 is 
 [[1 4]
 [2 5]
 [3 6]]  with dimensions  (3, 2)
Stacked array 3 is 
 [[1 4]
 [2 5]
 [3 6]]  with dimensions  (3, 2)


In [ ]:

# Stacking Numpy Arrays

array1 = np.random.randint(3, size = (3, 4, 5))
print("Array 1 has dimensions ", array1.shape, "\n")

array2 = np.random.randint(4, size = (3, 4, 5))
print("Array 2 has dimensions ", array2.shape, "\n")

stacked_array1 = np.stack((array1, array2), axis = 0)
print("Stacked array 1 has dimensions", stacked_array1.shape, "\n")

stacked_array2 = np.stack((array1, array2), axis = 1) 
print("Stacked array 2 has dimensions", stacked_array2.shape, "\n")

stacked_array3 = np.stack((array1, array2), axis = 2) 
print("Stacked array 3 has dimensions", stacked_array3.shape, "\n")

stacked_array4 = np.stack((array1, array2), axis = -1)
print("Stacked array 4 has dimensions", stacked_array4.shape, "\n")



Array 1 has dimensions  (3, 4, 5) 

Array 2 has dimensions  (3, 4, 5) 

Stacked array 1 has dimensions (2, 3, 4, 5) 

Stacked array 2 has dimensions (3, 2, 4, 5) 

Stacked array 3 has dimensions (3, 4, 2, 5) 

Stacked array 4 has dimensions (3, 4, 5, 2) 



###5c. Repeat

The repeat operation repeats elements of an array. The number of repetitions for each element is broadcasted to fit the shape of the given axis. The axis parameter specifies along which axis to repeat values. By default, it uses the flattened input array, and return a flat output array.

In [ ]:

# Repeat in Numpy Arrays

original_array = np.array([[1,2],[3,4]])
print("Array is \n", original_array, " with dimensions ", original_array.shape, "\n")

repeated_array1 = np.repeat(original_array, 2)
print("Repeated array 1 is \n", repeated_array1, "\n\n", "and the dimensions of the repeated array 1 are: \n", repeated_array1.shape, "\n")

repeated_array2 = np.repeat(original_array, 3, axis=0)
print("Repeated array 2 is \n", repeated_array2, "\n\n", "and the dimensions of the repeated array 2 are: \n", repeated_array2.shape, "\n")

repeated_array3 = np.repeat(original_array, 3, axis=1)
print("Repeated array 3 is \n", repeated_array3, "\n\n", "and the dimensions of the repeated array 3 are: \n", repeated_array3.shape, "\n")

repeated_array4 = np.repeat(original_array, [2,3], axis=0)
print("Repeated array 4 is \n", repeated_array4, "\n\n", "and the dimensions of the repeated array 4 are: \n", repeated_array4.shape, "\n")


Array is 
 [[1 2]
 [3 4]]  with dimensions  (2, 2) 

Repeated array 1 is 
 [1 1 2 2 3 3 4 4] 

 and the dimensions of the repeated array 1 are: 
 (8,) 

Repeated array 2 is 
 [[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 

 and the dimensions of the repeated array 2 are: 
 (6, 2) 

Repeated array 3 is 
 [[1 1 1 2 2 2]
 [3 3 3 4 4 4]] 

 and the dimensions of the repeated array 3 are: 
 (2, 6) 

Repeated array 4 is 
 [[1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 

 and the dimensions of the repeated array 4 are: 
 (5, 2) 



# 6. Math operations

In this section we will cover some commonly used mathematical operations
1. Broadcasting
1. Point-wise/element-wise operations
1. Redution operations
1. Comparison operations
1. Vector/Matrix operations

## a. Broadcasting

In [ ]:
# Broadcasting b/w arrays of different dimensions
# Note: When broadting two multi-dimensional tensors, match their corresponding dimensions beginning from the last dimension.
# All dimensions should either match or one of the arrays should have length 1 in that specific dimension

row_arr = np.random.rand(1,3)
print("A row array: \n", row_arr, " with dimensions ", row_arr.shape, "\n")
col_arr = np.random.rand(4,1)
print("A column array: \n", col_arr, " with dimensions ", col_arr.shape, "\n")

add_arr = row_arr + col_arr
print("row array + column array = ")
print(add_arr," with dimensions ", add_arr.shape, "\n")
mul_arr = row_arr * col_arr
print("row array * column array = ")
print(mul_arr," with dimensions ", mul_arr.shape, "\n")


A row array: 
 [[0.94466892 0.52184832 0.41466194]]  with dimensions  (1, 3) 

A column array: 
 [[0.26455561]
 [0.77423369]
 [0.45615033]
 [0.56843395]]  with dimensions  (4, 1) 

row array + column array = 
[[1.20922453 0.78640393 0.67921755]
 [1.71890261 1.29608201 1.18889563]
 [1.40081925 0.97799865 0.87081227]
 [1.51310287 1.09028227 0.98309589]]  with dimensions  (4, 3) 

row array * column array = 
[[0.24991746 0.1380579  0.10970114]
 [0.7313945  0.40403255 0.32104524]
 [0.43091104 0.23804129 0.18914818]
 [0.53698188 0.2966363  0.23570792]]  with dimensions  (4, 3) 



## b.Element-wise operations

In [ ]:
rand_arr_1 = np.random.rand(2,3)
print("A random array1 : \n", rand_arr_1, " with dimensions ", rand_arr_1.shape, "\n")
rand_arr_2 = np.random.rand(2,3)
print("A random array2 : \n", rand_arr_2, " with dimensions ", rand_arr_2.shape, "\n")
scalar = 5.0

# Addition with Scalars
new_arr_1 = rand_arr_1 + scalar
print("random array1 + 5.0 =")
print(new_arr_1, "\n")

# Multiplication with Scalars
new_arr_2 = rand_arr_1 * scalar
print("random array1 * 5.0 =")
print(new_arr_2, "\n")

# Elementwise Addition of Arrays
new_arr_3 = rand_arr_1 + rand_arr_2
print("random array1 + random array2 =")
print(new_arr_3, "\n")

# Elementwise Multiplication of Arrays aka Hadmard Product
new_arr_4 = rand_arr_1 * rand_arr_2
print("random array1 * random array2 =")
print(new_arr_4, "\n") # also equivalent to np.multiply(array1, array2)

# Absolute value
new_arr_5 = np.abs(-10*rand_arr_1)
print("abs (-10 * random array1) =")
print(new_arr_5, "\n")

# Square root value
new_arr_6 = np.sqrt(rand_arr_1)
print('sqrt(random array1) = \n', new_arr_6, "\n")

A random array1 : 
 [[0.0187898  0.6176355  0.61209572]
 [0.616934   0.94374808 0.6818203 ]]  with dimensions  (2, 3) 

A random array2 : 
 [[0.3595079  0.43703195 0.6976312 ]
 [0.06022547 0.66676672 0.67063787]]  with dimensions  (2, 3) 

random array1 + 5.0 =
[[5.0187898  5.6176355  5.61209572]
 [5.616934   5.94374808 5.6818203 ]] 

random array1 * 5.0 =
[[0.093949   3.08817749 3.06047861]
 [3.08466998 4.71874039 3.4091015 ]] 

random array1 + random array2 =
[[0.3782977  1.05466745 1.30972692]
 [0.67715947 1.61051479 1.35245817]] 

random array1 * random array2 =
[[0.00675508 0.26992645 0.42701707]
 [0.03715514 0.62925981 0.45725451]] 

abs (-10 * random array1) =
[[0.187898   6.17635497 6.12095723]
 [6.16933997 9.43748079 6.81820299]] 

sqrt(random array1) = 
 [[0.13707589 0.78589789 0.78236547]
 [0.78545146 0.97146697 0.82572411]] 



## c.Reduction

In [ ]:
rand_arr = np.random.rand(2,3)
print('random array: \n', rand_arr, "\n")

max_val = np.max(rand_arr)
print('Maximum value of array \n', max_val, "\n")
min_val = np.min(rand_arr)
print('Minimum value of array \n', min_val, "\n")

sum_val = np.sum(rand_arr)
print('Sum of array \n', sum_val, "\n")
max_idx = np.argmax(rand_arr, axis=0)
print('Maximum value\'s index of array along axis 0 \n', max_idx, "\n")
min_idx = np.argmin(rand_arr, axis=1)
print('Minimum value\'s index of array along axis 1 \n', min_idx, "\n")

mean_val = np.mean(rand_arr)
print('Mean value of array \n', mean_val, "\n")
std_val = np.std(rand_arr)
print('Standard deviation value of array \n', std_val, "\n")
norm_val = np.linalg.norm(rand_arr)
print('Norm value of array \n', norm_val, "\n")

random array: 
 [[0.21038256 0.1289263  0.31542835]
 [0.36371077 0.57019677 0.43860151]] 

Maximum value of array 
 0.5701967704178796 

Minimum value of array 
 0.1289262976548533 

Sum of array 
 2.0272462644757008 

Maximum value's index of array along axis 0 
 [1 1 1] 

Minimum value's index of array along axis 1 
 [1 0] 

Mean value of array 
 0.3378743774126168 

Standard deviation value of array 
 0.14445556227437842 

Norm value of array 
 0.9000883436106821 



## d.Comparision

In [ ]:
rand_arr_1 = np.random.rand(2,3)
print('random array1: \n', rand_arr_1, '\n')
rand_arr_2 = np.random.rand(2,3)
print('random array2: \n', rand_arr_2, '\n')

# Element-wise Comparison Operations
greater_compare = rand_arr_1 > rand_arr_2
print('random array1 > random array2')
print(greater_compare, '\n')

less_compare = rand_arr_1 < rand_arr_2
print('random array1 < random array2')
print(less_compare, '\n')

not_equal_compare = rand_arr_1 != rand_arr_2
print('random array1 != random array2')
print(not_equal_compare, '\n')

# Combining reduction operations with boolean arrays
print("any values for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(), "\n")

print("all values for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).all(), "\n")

print("any values along first axis for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(axis=0), "\n")

print("any values along second axis for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(axis=1), "\n")

print("any values for random array1 != random array2:")
print((rand_arr_1 != rand_arr_2).any(), "\n")

print("all values for random array1 != random array2:")
print((rand_arr_1 != rand_arr_2).all(), "\n")

random array1: 
 [[0.98837384 0.10204481 0.20887676]
 [0.16130952 0.65310833 0.2532916 ]] 

random array2: 
 [[0.46631077 0.24442559 0.15896958]
 [0.11037514 0.65632959 0.13818295]] 

random array1 > random array2
[[ True False  True]
 [ True False  True]] 

random array1 < random array2
[[False  True False]
 [False  True False]] 

random array1 != random array2
[[ True  True  True]
 [ True  True  True]] 

any values for random array1 > random array2:
True 

all values for random array1 > random array2:
False 

any values along first axis for random array1 > random array2:
[ True False  True] 

any values along second axis for random array1 > random array2:
[ True  True] 

any values for random array1 != random array2:
True 

all values for random array1 != random array2:
True 



## e.Vector/Matrix operations

In [ ]:
# Vector x Vector
array1 = np.random.randn(3)
array2 = np.random.randn(3)

print('Array1 \n', array1, 'with dimension ', array1.shape, '\n')
print('Array2 \n', array2, 'with dimension ', array2.shape, '\n')

matmul_arr = np.matmul(array1, array2)
another_arr = array1@array2
print('Matmul of the two arrays can be derived by using np.matmul(array1, array2) \n', matmul_arr)
print("Matmul of the two arrays can also be derived by using array1@array2 \n", another_arr)
print('Dimensions of resulting product: \n', matmul_arr.shape)

# Matrix x Vector
array3 = np.random.randn(3, 4)
array4 = np.random.randn(4)

print('Array3 \n', array3, 'with dimension ', array3.shape, '\n')
print('Array4 \n', array4, 'with dimension ', array4.shape, '\n')

matmul_arr = np.matmul(array3, array4)
another_arr = array3@array4
print('Matmul of a vector and a matrix can be derived by using np.matmul(array3, array4) \n', matmul_arr)
print('Matmul of a vector and a matrix can also be derived by using array3@array4 \n', another_arr)
print('Dimensions of resulting product: \n', matmul_arr.shape)

# Matrix x Matrix 

matrix1 = np.random.randint(4, size = (2, 3))
matrix2 = np.random.randint(4, size = (3, 2))

print('Matrix1 \n', matrix1, 'with dimension ', matrix1.shape, '\n')
print('Matrix2 \n', matrix2, 'with dimension ', matrix2.shape, '\n')

matmul_mat = np.matmul(matrix1, matrix2)
print('Matmul of two matrices can be derived by using np.matmul(matrix1, matrix2) \n', matmul_mat)
print('Dimensions of resulting product: \n', matmul_mat.shape, "\n")

Array1 
 [-0.51080514 -1.18063218 -0.02818223] with dimension  (3,) 

Array2 
 [0.42833187 0.06651722 0.3024719 ] with dimension  (3,) 

Matmul of the two arrays can be derived by using np.matmul(array1, array2) 
 -0.3058508256835472
Matmul of the two arrays can also be derived by using array1@array2 
 -0.3058508256835472
Dimensions of resulting product: 
 ()
Array3 
 [[-0.63432209 -0.36274117 -0.67246045 -0.35955316]
 [-0.81314628 -1.7262826   0.17742614 -0.40178094]
 [-1.63019835  0.46278226 -0.90729836  0.0519454 ]] with dimension  (3, 4) 

Array4 
 [ 0.72909056  0.12898291  1.13940068 -1.23482582] with dimension  (4,) 

Matmul of a vector and a matrix can be derived by using np.matmul(array3, array4) 
 [-0.83148203 -0.11722929 -2.22679112]
Matmul of a vector and a matrix can also be derived by using array3@array4 
 [-0.83148203 -0.11722929 -2.22679112]
Dimensions of resulting product: 
 (3,)
Matrix1 
 [[3 0 0]
 [2 0 2]] with dimension  (2, 3) 

Matrix2 
 [[3 2]
 [2 3]
 [0 0]] with 

In [ ]:
rand_mat_1 = np.random.rand(4,2)
rand_mat_2 = np.random.rand(2,3)
print('Matrix1 \n', rand_mat_1, 'with dimension ', rand_mat_1.shape, '\n')
print('Matrix2 \n', rand_mat_2, 'with dimension ', rand_mat_2.shape, '\n')

# dot product
dot_mat = np.dot(rand_mat_1, rand_mat_2)
another_mat = rand_mat_1@rand_mat_2
print('Dot product of two matrices can be derived by using np.dot(mat1, mat2) \n', dot_mat)
print('Dot product of two matrices can also be derived by using mat1@mat2 \n', another_mat)
print('Dimensions of resulting product: \n', dot_mat.shape)

a = np.ones([9, 5, 7, 4])
b = np.ones([9, 5, 4, 3])
print('array1 \'s dimension ', a.shape, '\n')
print('array2 \'s dimension ', b.shape, '\n')

# matmul with multi-dimenstion arrays
c = np.matmul(a,b)
print('Matmul of two multi-dimension arrays can be derived by using np.matmul(array1, array2) \n')
print('Dimensions of resulting product: \n', c.shape)

Matrix1 
 [[0.82894003 0.00469548]
 [0.67781654 0.27000797]
 [0.73519402 0.96218855]
 [0.24875314 0.57615733]] with dimension  (4, 2) 

Matrix2 
 [[0.59204193 0.57225191 0.22308163]
 [0.95274901 0.44712538 0.84640867]] with dimension  (2, 3) 

Dot product of two matrices can be derived by using np.dot(mat1, mat2) 
 [[0.49524087 0.47646198 0.18889559]
 [0.65854564 0.50860922 0.37974551]
 [1.35198987 0.8509351  0.97841301]
 [0.69620562 0.39996403 0.54315682]]
Dot product of two matrices can also be derived by using mat1@mat2 
 [[0.49524087 0.47646198 0.18889559]
 [0.65854564 0.50860922 0.37974551]
 [1.35198987 0.8509351  0.97841301]
 [0.69620562 0.39996403 0.54315682]]
Dimensions of resulting product: 
 (4, 3)
array1 's dimension  (9, 5, 7, 4) 

array2 's dimension  (9, 5, 4, 3) 

Matmul of two multi-dimension arrays can be derived by using np.matmul(array1, array2) 

Dimensions of resulting product: 
 (9, 5, 7, 3)


###Tensordot

Understanding tensordot function will help you in writing succint code for your homeworks especially in Convolutional Neural Net assignment.

To give a brief overview: 
We input the arrays and the respective axes along which the sum-reductions are intended. The axes that take part in sum-reduction are removed in the output and all of the remaining axes from the input arrays are spread-out as different axes in the output keeping the order in which the input arrays are fed.

To understand in depth please checkout: https://stackoverflow.com/questions/41870228/understanding-tensordot

In [ ]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
print('A \'s dimension ', a.shape, '\n')
print('B \'s dimension ', b.shape, '\n')

# compute tensor dot product along specified axes.
c = np.tensordot(a,b, axes=([1,0],[0,1]))
print("A⨂B =\n", c, ' with dimension', c.shape, '\n')

# this equals to 
d = np.zeros((5,2))
for i in range(5):
  for j in range(2):
    for k in range(3):
      for n in range(4):
        d[i,j] += a[k,n,i] * b[n,k,j]
print("tensor dot is equal to sum over certain dimensions.\n")
print(c==d)

A 's dimension  (3, 4, 5) 

B 's dimension  (4, 3, 2) 

A⨂B =
 [[4400. 4730.]
 [4532. 4874.]
 [4664. 5018.]
 [4796. 5162.]
 [4928. 5306.]]  with dimension (5, 2) 

tensor dot is equal to sum over certain dimensions.

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
