In [ ]:
# 텐서플로를 사용한 사용자 정의 모델과 훈련

In [ ]:
# 텐서와 넘파이

In [ ]:
# 넘파이처럼 텐서플로 사용하기

In [3]:
import tensorflow as tf

t = tf.constant([[1,2,3],[4,5,6]])

In [4]:
tf.constant(t[1])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [5]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
# 텐서와 넘파이

In [6]:
t.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [ ]:
# 타입변환

In [7]:
t2 = tf.constant(40, dtype=tf.float64)

tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [ ]:
# 변수

In [8]:
v=tf.Variable([[1.,2.,3.],[4., 5., 6.]])

In [9]:
v.assign(2+v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[3., 4., 5.],
       [6., 7., 8.]], dtype=float32)>

In [11]:
v[1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([6., 7., 8.], dtype=float32)>

In [10]:
v[0,1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 3., 42.,  5.],
       [ 6.,  7.,  8.]], dtype=float32)>

In [15]:
v.scatter_nd_update(indices=[[0,0], [1,2]], updates=[100., 200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   5.],
       [  6.,   7., 200.]], dtype=float32)>

In [ ]:
# 다른 데이터 구조

In [19]:
s=tf.SparseTensor(indices=[[0,1], [1,0], [2,3]],
                  values = [1., 2., 3.],
                  dense_shape=[3,4])

In [20]:
print(s)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [ ]:
# tf.sparse패키지는 희소 텐서를 위한 연산을 제공

In [21]:
tf.sparse.to_dense(s)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [2., 0., 0., 0.],
       [0., 0., 0., 3.]], dtype=float32)>

In [ ]:
# 텐서 배열

In [32]:
array = tf.TensorArray(dtype=tf.float32, size=3)
array = array.write(0,tf.constant([1.,2.]))
array = array.write(1,tf.constant([3.,10.]))
array = array.write(2,tf.constant([5.,7.]))

In [34]:
array.read(1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 3., 10.], dtype=float32)>

In [35]:
array.stack()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [0., 0.],
       [5., 7.]], dtype=float32)>

In [30]:
mean, variance = tf.nn.moments(array.stack(), axes=0)
mean

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [31]:
variance

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.6666665, 8.666667 ], dtype=float32)>