In [ ]:
# 넘파이로 텐서 공부

In [1]:
import sklearn
import tensorflow as tf

In [2]:
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

In [3]:
%matplotlib inline

In [4]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

iris = load_iris()
#iris.data -> iris['data']
#iris.target.shape -> (150,)

X = iris.data[:, (2, 3)] # 꽃잎 길이, 꽃잎 너비

y = (iris.target == 0).astype(int)

per_clf = Perceptron(max_iter=1000, tol=1e-3, random_state=42)
per_clf.fit(X, y)

y_pred = per_clf.predict([[2, 0.5]])
#2*(-1.4)+(0.5)*(-2.2)+4


In [ ]:
# help(per_clf)

In [5]:
per_clf.coef_

array([[-1.4, -2.2]])

In [ ]:
per_clf.intercept_

array([4.])

In [ ]:
V = np.array([[-1.4],[-2.2]])
V

array([[-1.4],
       [-2.2]])

In [ ]:
b=4

In [ ]:
y_pred
#2*(-1.4)+(0.5)*(-2.2)+4

array([1])

In [ ]:
per_clf.predict([[2, 1.5]])
#2*(-1.4)+(1.5)*(-2.2)+4

array([0])